version: '3.8'
services:
  passenger-postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=passengerdb'
      - 'POSTGRES_PASSWORD=postgre'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5452:5432'

  driver-postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=driverdb'
      - 'POSTGRES_PASSWORD=postgre'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5442:5432'