version: '3.8'
services:

  passenger-postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=passengerdb'
      - 'POSTGRES_PASSWORD=postgre'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5452:5432'

  driver-postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=driverdb'
      - 'POSTGRES_PASSWORD=postgre'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5442:5432'

  ride-postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=ridedb'
      - 'POSTGRES_PASSWORD=postgre'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5454:5432'

  payment-postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=paymentdb'
      - 'POSTGRES_PASSWORD=postgre'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5455:5432'



  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"

  kafka:
    image: obsidiandynamics/kafka
    container_name: kafka
    restart: "no"
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_INTERNAL:PLAINTEXT,DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: DOCKER_INTERNAL://:29092,DOCKER_EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: DOCKER_INTERNAL://kafka:29092,DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper



  driver:
    build:
      dockerfile: ./driver-service/Dockerfile
    ports:
      - '5555:5555'
    environment:
      DB_HOST: "driver-postgres"
      DB_PORT: "5442"
      DB_DATABASE: "driverdb"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgre"
    depends_on:
      - driver-postgres    


  passenger:
    build:
      dockerfile: ./passenger-service/Dockerfile
    ports:
      - '4444:4444'
    environment:
      DB_HOST: "passenger-postgres"
      DB_PORT: "5452"
      DB_DATABASE: "passengerdb"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgre"
    depends_on:
      - passenger-postgres
      - kafka    

  ride:
    build:
      dockerfile: ./ride-service/Dockerfile
    ports:
      - '3333:3333'
    environment:
      DB_HOST: "ride-postgres"
      DB_PORT: "5454"
      DB_DATABASE: "ridedb"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgre"
    depends_on:
      - ride-postgres
      - driver
      - passenger
      - payment  

  payment:
    build:
      dockerfile: ./payment-service/Dockerfile
    ports:
      - '1111:1111'
    environment:
      DB_HOST: "payment-postgres"
      DB_PORT: "5455"
      DB_DATABASE: "paymentdb"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgre"
    depends_on:
      - payment-postgres    
